export const FETCH_CLASSES = 'FETCH_CLASSES';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const PUT_ID = 'PUT_ID';
export const REGISTER_COMPLETE = 'REGISTER_COMPLETE';
export const FAILED_REGISTER = 'FAILED_REGISTER';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const FETCH_PARTICIPANTS= 'FETCH_PARTICIPANTS';
export const FETCH_INSTRUCTORS= 'GETCH_INSTRUCTORS';