export const GET_CLASSES = 'GET_CLASSES';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const PUT_ID = 'PUT_ID';
export const REGISTER_COMPLETE = 'REGISTER_COMPLETE';
export const FAILED_REGISTER = 'FAILED_REGISTER';
export const ENTERED_WAITINGLIST = 'ENTERED_WAITINGLIST';